version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Montar o arquivo de configuração do Nginx
      - static-volume:/usr/share/nginx/html/static  # Montar o volume de arquivos estáticos
    ports:
      - "80:80"  # Expor a porta 80
  web:
    build: .
    command: >
      sh -c "gunicorn -b 0.0.0.0:8000 tracking.wsgi:application"
    depends_on:
      - redis
      - celery_worker
    volumes:
      - .:/app
      - static-volume:/app/staticfiles

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: >
      sh -c "celery -A tracking worker --loglevel=info"
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: >
      sh -c "celery -A tracking beat --loglevel=info"
    volumes:
      - .:/app
volumes:
  static-volume: