# Generated by Django 3.2.20 on 2023-08-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commons', '0002_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
