# Generated by Django 3.2.20 on 2023-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commons', '0004_auto_20230806_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-sale_date',), 'verbose_name': 'Venda'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-created_date',), 'verbose_name': 'Loja'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['updated_at'], 'verbose_name': 'Rastreamento'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
