# Generated by Django 3.2.20 on 2023-08-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commons', '0005_auto_20230808_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_imgs/'),
        ),
    ]
