# Generated by Django 3.2.20 on 2023-08-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('commons', '0006_shop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='premium_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
