# Generated by Django 3.2.20 on 2023-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0007_shop_premium_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
