name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t tracking-app:latest .
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin https://131643625257.dkr.ecr.us-east-1.amazonaws.com
        docker tag tracking-app:latest 131643625257.dkr.ecr.us-east-1.amazonaws.com/tracking-app:latest
        docker push 131643625257.dkr.ecr.us-east-1.amazonaws.com/tracking-app:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        ECR_REPOSITORY_NAME: tracking-app  # Substitua pelo nome do seu repositório ECR


    - name: Configure AWS Elastic Beanstalk
      run: |
        eb init -p docker TrackingApp --region us-east-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Create Elastic Beanstalk Environment
      run: |
        eb create TrackingAppEnvironment -c TrackingApp --cname tracking-app --instance_type t2.micro --scale 1 --elb-type application
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Deploy Docker image to Elastic Beanstalk
      run: |
        eb deploy TrackingAppEnvironment --label tracking-app:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1