name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # ou a branch de sua escolha

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Escolha a versão do Python que você está usando

    - name: Install AWS CLI and EB CLI
      run: |
        pip install awscli
        pip install awsebcli
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Substitua pela região AWS correta

    - name: Configure AWS Elastic Beanstalk
      run: |
        eb init -p python-3.9 YourElasticBeanstalkApplicationName --region us-east-1
        eb use YourElasticBeanstalkEnvironmentName
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Substitua pela região AWS correta

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        eb deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1  # Substitua pela região AWS correta
